# pfSense Playbook
#

- name: pfSense Playbook
  hosts: pfSense
  gather_facts: false
  roles:
    #- update

- name: pfSense Update - Repository Update
  shell: pkg update

- name: pfSense Upgrade - System Upgrade
  shell: pkg upgrade -y
